// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjYtGf5nZqVuq8keYL5wbZg4TZOB90eV8',
    appId: '1:900352737743:web:a6542ea0a432a44a3f12ba',
    messagingSenderId: '900352737743',
    projectId: 'xstock-73a4b',
    authDomain: 'xstock-73a4b.firebaseapp.com',
    storageBucket: 'xstock-73a4b.appspot.com',
    measurementId: 'G-MT5SX8YVQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlWW64a3Jk4wNOtNgW24cmayau3C-qvAU',
    appId: '1:900352737743:android:55200675936c86723f12ba',
    messagingSenderId: '900352737743',
    projectId: 'xstock-73a4b',
    storageBucket: 'xstock-73a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw0wttRYxvz4vj5hrP6no6SZjUD06Q27Q',
    appId: '1:900352737743:ios:a1b074d36341cb213f12ba',
    messagingSenderId: '900352737743',
    projectId: 'xstock-73a4b',
    storageBucket: 'xstock-73a4b.appspot.com',
    iosBundleId: 'com.appgemz.xstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw0wttRYxvz4vj5hrP6no6SZjUD06Q27Q',
    appId: '1:900352737743:ios:a1b074d36341cb213f12ba',
    messagingSenderId: '900352737743',
    projectId: 'xstock-73a4b',
    storageBucket: 'xstock-73a4b.appspot.com',
    iosBundleId: 'com.appgemz.xstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjYtGf5nZqVuq8keYL5wbZg4TZOB90eV8',
    appId: '1:900352737743:web:085ffbbb4a20d9aa3f12ba',
    messagingSenderId: '900352737743',
    projectId: 'xstock-73a4b',
    authDomain: 'xstock-73a4b.firebaseapp.com',
    storageBucket: 'xstock-73a4b.appspot.com',
    measurementId: 'G-0X5MK5HG2Q',
  );
}
